# Generated by Django 4.0.4 on 2022-05-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quad_dj_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'profile_words',
                'ordering': ('profile', 'word'),
            },
        ),
        migrations.RemoveField(
            model_name='word',
            name='first_letter',
        ),
        migrations.RemoveField(
            model_name='word',
            name='last_letter',
        ),
        migrations.RemoveField(
            model_name='word',
            name='length',
        ),
        migrations.AddField(
            model_name='profile',
            name='words_solved',
            field=models.ManyToManyField(through='quad_dj_app.ProfileWords', to='quad_dj_app.word'),
        ),
        migrations.AddField(
            model_name='word',
            name='l1',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='word',
            name='l2',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='word',
            name='l3',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='word',
            name='l4',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='word',
            name='l5',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='profilewords',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quad_dj_app.profile'),
        ),
        migrations.AddField(
            model_name='profilewords',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quad_dj_app.word'),
        ),
    ]
