# Generated by Django 4.0.4 on 2022-05-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quad_dj_app', '0002_profilewords_remove_word_first_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='l1',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='l2',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='l3',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='l4',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='l5',
            field=models.CharField(max_length=1),
        ),
    ]
