# Generated by Django 4.0.4 on 2022-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quad_dj_app', '0003_alter_word_l1_alter_word_l2_alter_word_l3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'vocabs',
                'ordering': ('name',),
            },
        ),
    ]
